name: NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Lua/Lua.csproj

      - name: Test
        run: dotnet test tests/Lua.Tests/Lua.Tests.csproj -c Release --no-restore --filter "TestCategory!=ExpectedFailure"

      - name: Pack
        run: dotnet pack src/Lua/Lua.csproj -c Release --no-restore -o ./artifacts/nuget

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/nuget/*.nupkg

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push "artifacts/nuget/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
